//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementApp.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string JobPosition { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.Guid EmployeeId { get; set; }
    }
}
