//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementApp.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicHoliday
    {
        public int HolidayId { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public string Description { get; set; }
        public bool IsRecurring { get; set; }
    }
}
